silverstripe/silverstripe-behat-extension

src/SilverStripe/BehatExtension/Context/LoginContext.php
Changed from 'secret' to 'Secret!123'.
For example, the CWP default configuration increases the required
complexity to include uppercase letters, see https://gitlab.cwp.govt.nz/cwp/cwp-core/blob/master/_config.php#L134
The current behaviour is that the login form simply submits to an empty page when the `cwp-core` module is installed.
This should not impact existing tests since the password is only used
indirectly, through "Given I login with ADMIN permissions".
The change also removes the password encryption to make the password a bit more obvious when devs are debugging the test databases. We already test password encryption extensively, so keeping it encrypted in Behat tests is of limited additional value IMHO.
@tractorcow @jeffreyguo Could you peer review please?
=> More complex password default to comply with custom authenticators

src/SilverStripe/BehatExtension/Utility/TestMailer.php
I just noticed the testmailer.php has not been updated according to the latest from SilverStripe Frramework (/framework/email/Email.php), see below lines:
https://github.com/silverstripe/silverstripe-framework/blob/3.2/email/Email.php#L84
https://github.com/silverstripe/silverstripe-framework/blob/3.2/email/Email.php#L89
Now I updated the two parameters $attachedFiles and $customHeaders to be array. Please have a check.
=> update the params to be array on sending email

src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
The issue that prompted this change was that at line 361, if an exception needed to be thrown, it would be thrown with $field being a NodeElement rather than a string, causing a Catchable Fatal Error to be thrown in ElementNotFoundException::__construct#46 (can't convert object of type NodeElement to string).
=> FIX logic error where a variable is used for two purposes

src/SilverStripe/BehatExtension/Compiler/CoreInitializationPass.php
Moved from TestRunner to SapphireTest in 4.0. 
Required for https://github.com/silverstripe/silverstripe-framework/pull/4404, but can be merged before this other PR (since it'll just fall back to using `TestRunner`). Implemented it this way to avoid creating a 3.x compat branch for Behat
=> Comply with moved use_test_manifest() method

src/SilverStripe/BehatExtension/Context/FixtureContext.php
Fixes regression caused by 8d49da260988b1cee1eac420f37bfe80d4c0eb6b
prepareAsset('Folder','some/folder') would create some/folder/folder due to wrong ParentID relations.
Also set the 'ID' of folders to avoid creating them again.
=> Fix nested folder fixture creation

src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
This may be carry over from PHPUnit sessions. Changing context to $state to match other env values so a default fixture can be defined through getTestSessionState.
=> FIX: params isn't defined in this context

src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
We had a 404 issue in our behat tests which took forever to figure out. I thought I'd add a little wrapper function which might save someone some time debugging down the line.
=> ENH: adding wrapper around visit to detect 404s

src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
Reverts silverstripe-labs/silverstripe-behat-extension#96
Sometimes a 404 is needed and isn't necessarily an error case. :D
=> Revert "ENH: adding wrapper around visit to detect 404s"

README.md, src/SilverStripe/BehatExtension/Context/EmailContext.php
The existing step `I click on the "([^"]*)" link in the email` doesn't work for some special characters in the link text, e.g. the link text is as below in email:
`http://localhost/Security/changepassword?m=199&title=reset`
It doesn't match with anything like localhost, Security or changepassword, etc.
=> Add new step to click the http link address in email

composer.json, src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php, src/SilverStripe/BehatExtension/Context/BasicContext.php, src/SilverStripe/BehatExtension/Context/Initializer/SilverStripeAwareInitializer.php, src/SilverStripe/BehatExtension/Extension.php, src/SilverStripe/BehatExtension/services/silverstripe.yml
The bootstrap_file parameter specifies a PHP file that will be included
between Constants.php (which is included by the composer autoloader)
and Core.php (which is included by SilverStripeAwareInitializer).
The goal of this setting is to provide a bit more flexibility about how
behat test environments are set up. It’s the logical companion of
PHPUnit’s bootstrap property.
=> NEW: Add bootstrap_file extension parameter.

composer.json, src/SilverStripe/BehatExtension/Compiler/CoreInitializationPass.php, src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php, src/SilverStripe/BehatExtension/Context/Initializer/SilverStripeAwareInitializer.php, tests/bootstrap.php
FIX: Reply on Core/Core.php being in include path.
This lets us change the location of Core.php as long as we also
manipulate the include path.
This is necessary for silverstripe/silverstripe-framework#6266
This also tags a `2.1.x-dev` alias as we've added new features since 2.0
=> Core reference fix

README.md
Use composer to install Selenium, which allows us to just specify the latest stable release.
Add some notes around Travis compat, since that's bitten us before with core tests.
Also remove Saucelabs docs, they're not used
=> Document correct Firefox/Selenium, use composer

src/SilverStripe/BehatExtension/Context/FixtureContext.php
Unfortunately, named groups breaks all IDE autocompletion in PHPStorm, and the actual parser doesn’t benefit from them. Removing them makes it possible to navigate from gerkin fixtures to method implementations immediately. I've also removed all unnecessary nested groups for ease of readability.
=> ENHANCEMENT: Remove redundant named groups from patterns

composer.json
These composer dependencies were inlined from Behat in an attempt to 
lock in PHP 5.3-compatible versions of Symfony packages. This is no
longer relevant and so we can remove this.
Please not that after this is merged, we should tag 2.2.3 against master
=> FIX: Remove unnecessary dependencies.

src/SilverStripe/BehatExtension/Context/FixtureContext.php
Without this, `dirname('somefile.jpg')` was coming up with `.` and being created as a literal directory, which is assigned as a parent.
=> BUG Prevent top-level files being created with incorrect parent folder

src/SilverStripe/BehatExtension/Compiler/CoreInitializationPass.php
The lack of this env var causes config bootstrapping to, occasionally, enter an infinite loop.
=> BUG Ensure safe fallback for missing `.env` file to dev mode.

src/Controllers/ModuleSuiteLocator.php
If the suite is already loaded, you can't call registerSuiteConfiguration
a second time.
=> FIX: Don't load suite twice.

src/Context/SilverStripeContext.php
The SiteTree link still exists but the module
will work if SiteTree isn’t installed.
=> FIX: Soften coupling to SiteTree

src/Context/LoginContext.php
There is a minor change required for the behat-extension to work with the Authentication Refactor work.
This PR contains that change.
- The LoginForm has been renamed to `MemberLoginForm`
- Instead of trying to find by URL, find the form by ID
Build error is because it uses the wrong branch?
=> [WIP] Changes for Authenticator refactor

.travis.yml
I had noticed that behat-extensions was still downloading `alpha7` of `silverstripe-admin`... which is a bit incompatible with other modules using `dev-master`
=> Fix to download the proper version of silverstripe-admin

src/Context/LoginContext.php, src/Controllers/ModuleCommandTrait.php, src/Controllers/ModuleSuiteLocator.php, src/Extension.php
From https://github.com/silverstripe/silverstripe-framework/issues/6387
The change is to, instead of adding a new controller, replace the core controller, and take over full control of loading suites.
=> BUG Prevent behat from always running root behat.yml fixtures

README.md
Firefox 45.0 and 52.0 ESR aren't even loading the URLs (at least with Selenium 2.41).
See https://github.com/silverstripe/silverstripe-behat-extension/issues/162
This might be solved with upgrading to Selenium 2.x latest, but for now let's not confuse users.
I'm pretty familiar with all of this, and it still took me half an hour to figure out.
=> Link to correct Firefox download (fixes #162)

composer.json, src/Compiler/CoreInitializationPass.php, src/Compiler/MinkExtensionBaseUrlPass.php, src/Context/SilverStripeContext.php
Parent issue https://github.com/silverstripe/silverstripe-framework/issues/7478
Requires https://github.com/silverstripe/silverstripe-framework/pull/7484
=> Update to use new Environment::getenv()

src/Context/FixtureContext.php
This PR adds the ability to add an extension to an object with a step in a feature file. This is especially useful when a module provides an extension for use, but doesn't apply it to any existing extensible objects by default.
Example: 
```
Given I add an extension "DNADesign\Elemental\Extensions\ElementalPageExtension" to the "Page" class
And a "page" "Blocks Page" with a "Content Block" content element with "Some content" content
```
=> NEW Adding abilility to add an extension in a step

src/Context/BasicContext.php, src/Utility/StepHelper.php
This PR allows scenarios to tag themselves with `@unsavedChanges` meaning they will automatically dismiss any "Unsaved Changes!" modal that appears at the end of the test - preventing the error that could occur.
=> NEW Allows scenarios to anticipate an unsaved changes modal

src/Context/SilverStripeContext.php
Fixes https://github.com/silverstripe/silverstripe-admin/issues/778
=> ADD / After each step we wait for the server to handle all requests

composer.json
Following #185, the behat extension needs `silverstripe/testsession` 2.2 or greater.
* https://github.com/silverstripe/silverstripe-admin/issues/778
=> MINOR Increment testsession requirement for 4.1 release

.travis.yml, src/Context/BasicContext.php
Minor tweak so multiple button name can be specified when calling the the `I press the "..." button` rule
* https://github.com/silverstripe/silverstripe-admin/pull/956
=> BUG Update stepIPressTheButton to accept a list of button names separated by |

src/Context/SilverStripeContext.php
Mink does not autostart web driver session anymore until the first ->visit invocation
Here's the breaking change: https://github.com/minkphp/Mink/commit/acf5fb1ec70b7de4902daf75301356702a26e6da
SilverStripeContext assumes the session is started when it prepares for the scenario (e.g. it may change the resolution)
=> Fix WebDriverSession autostart

.travis.yml, composer.json, tests/php/SilverStripeContextTest.php
PHPUnit 7 is no longer supported and there are bugs that we need to fix in the master test suites that fail because we aren't using phpunit 8
=> Bump min-php and phpunit versions
