README.md

Selenium releases have moved, see: https://code.google.com/p/selenium/downloads/list

FIX: broken link to selenium server jar file

---

docs/tutorial.md

Matches the one in the main Readme

DOCS: Updated definition check

---

src/SilverStripe/BehatExtension/Context/BasicContext.php

Every once in a while something falls over due to the inherent unreliability of webdriver and the browser, and this catches it and lets the test suite continue to the next scenario rather than just falling over completely. 
-- P.S. just found this handy tip too, you can do a compare on github ignoring whitespace by adding ?w=1, e.g. https://github.com/silverstripe-labs/silverstripe-behat-extension/compare/master...IgorNadj:patch-safety?w=1

ENH: adding safety try-catch blocks to prevent whole test suite from falling over

---

README.md
src/SilverStripe/BehatExtension/Context/BasicContext.php

This commit uses terminology which assumes https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/98 gets merged

Add ability to confirm/dismiss dialogs after clicking in elements

---

src/SilverStripe/BehatExtension/Context/Initializer/SilverStripeAwareInitializer.php

add condition to prevent running endTestSession() twice

---

README.md
src/SilverStripe/BehatExtension/Context/EmailContext.php

Find an email by three fields in one step: from address, to address and title

Find email by title then check the recipents

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php

Correctly create published files, and delete them via the AssetStore API rather than unlink(). Since the merge of https://github.com/silverstripe/silverstripe-cms/pull/1381 cms Behat builds are broken due to this. Figured I'd open the PR before its ready to avoid the usual suspects (@dhensby and @tractorcow) toiling over the same problem :)
Again: This isn't ready to merge, work in progress.

WIP Fix SS4 AssetStore compat in FixtureContext

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php

- Don't delete Folders (managed by backend)
- Fix deletion to match correct columns
- New assertion for matching files by filename and hash
- Skip createdFilesPath - Managed by backend not by behat anymore

BUG Compatibility with 4.0 AsetStore API

---

.editorconfig
src/SilverStripe/BehatExtension/Context/LoginContext.php
tests/Context/SilverStripeContextTest.php

Merge up into master later.
@dhensby can you please test this locally? Don't worry, behat is only hard the first time. :)

API Respect CSRF on login form

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php
src/SilverStripe/BehatExtension/Context/LoginContext.php

See https://github.com/silverstripe/silverstripe-framework/pull/5734

Update to support new namespace SilverStripe\ORM

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php
src/SilverStripe/BehatExtension/Context/LoginContext.php

To be merged with https://github.com/silverstripe/silverstripe-framework/pull/5741
To be merged after https://github.com/silverstripe-labs/silverstripe-behat-extension/pull/117

API Apply SilverStripe\Security namespace

---

src/SilverStripe/BehatExtension/Context/BasicContext.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/5795 to pass

Search for table title with class contains 'title', rather than class == 'title'

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php

Dependency of https://github.com/silverstripe/silverstripe-cms/issues/1572
The old ->publish() api is deprecated.
The below code also assumed that class == table, and did not use parameterised queries.

Update use of versioned API and respect table_name

---

src/SilverStripe/BehatExtension/Compiler/CoreInitializationPass.php
src/SilverStripe/BehatExtension/Compiler/MinkExtensionBaseUrlPass.php
src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
src/SilverStripe/BehatExtension/Console/Processor/LocatorProcessor.php
src/SilverStripe/BehatExtension/Context/BasicContext.php
src/SilverStripe/BehatExtension/Context/ClassGuesser/ModuleContextClassGuesser.php
src/SilverStripe/BehatExtension/Context/EmailContext.php
src/SilverStripe/BehatExtension/Context/FixtureContext.php
src/SilverStripe/BehatExtension/Context/Initializer/SilverStripeAwareInitializer.php
src/SilverStripe/BehatExtension/Context/LoginContext.php
src/SilverStripe/BehatExtension/Context/SilverStripeAwareContextInterface.php
src/SilverStripe/BehatExtension/Context/SilverStripeContext.php
src/SilverStripe/BehatExtension/Utility/TestMailer.php

Merge with https://github.com/silverstripe/silverstripe-framework/pull/5921

Update for framework namespacing

---

src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
src/SilverStripe/BehatExtension/Console/Processor/LocatorProcessor.php

Merge with https://github.com/silverstripe/silverstripe-framework/pull/5974

Rename SS_ prefixed classes

---

src/SilverStripe/BehatExtension/Context/SilverStripeContext.php

See https://github.com/silverstripe/silverstripe-behat-extension/issues/133

Corrected variable name in givenTheCurrentTimeIs to address error in v1.0

---

src/SilverStripe/BehatExtension/Context/BasicContext.php

See https://github.com/silverstripe/silverstripe-framework/pull/6434
Moved `iShouldSeeAButton` from CmsContext to this module.

Update behat extension for updated button styling

---

src/SilverStripe/BehatExtension/Utility/TestMailer.php

This means that Mailer can be refactored and this will still work.
Merge after https://github.com/silverstripe/silverstripe-framework/pull/6483
and before https://github.com/silverstripe/silverstripe-framework/pull/6466

NEW: Refactor TestMailer to extend from the default

---

src/SilverStripe/BehatExtension/Context/BasicContext.php

Required for https://github.com/silverstripe/silverstripe-asset-admin/pull/360

API Add check for text in current alert

---

src/SilverStripe/BehatExtension/Compiler/CoreInitializationPass.php
src/SilverStripe/BehatExtension/Context/Initializer/SilverStripeAwareInitializer.php
src/SilverStripe/BehatExtension/services/silverstripe.yml

Required to get https://github.com/silverstripe/silverstripe-framework/issues/6641 working

Move bootstrap file up into correct point in application cycle

---

.travis.yml
src/SilverStripe/BehatExtension/Console/Processor/InitProcessor.php
src/SilverStripe/BehatExtension/Console/Processor/LocatorProcessor.php

Fixes for https://github.com/silverstripe/silverstripe-framework/pull/6706#discussion_r106293963
Tested locally to confirm it works. :)

Upgrade module loader manifest

---

.travis.yml
composer.json
tests/Context/SilverStripeContextTest.php

Allow behat to work with new PHPUnit versions

Bump PHPUnit dep

---

src/SilverStripe/BehatExtension/Context/FixtureContext.php

Requires https://github.com/silverstripe/silverstripe-framework/pull/6725

Update versioned namespace

---

.travis.yml
README.md
composer.json
docs/webservice-mocking.md
src/Context/FixtureContext.php

Required for https://github.com/silverstripe/silverstripe-framework/issues/6642

API Upgrade to use new AssetStore service name

---

.travis.yml
src/Compiler/CoreInitializationPass.php
src/Controllers/ModuleCommandTrait.php

Issue: https://github.com/silverstripe/silverstripe-framework/issues/6851
* https://github.com/silverstripe/silverstripe-framework/pull/6934 (also requires this PR 😄 )

API Consistent use of inst() naming across framework

---

src/Context/LoginContext.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/7028

Add logout form step

---

src/Compiler/CoreInitializationPass.php
src/Context/FixtureContext.php
src/Context/Initializer/SilverStripeAwareInitializer.php

Main issue: https://github.com/silverstripe/silverstripe-framework/issues/6681
See https://github.com/silverstripe/silverstripe-framework/pull/7037 for framework pull request

Updated behat-extension to use app object

---

src/Compiler/CoreInitializationPass.php

ƒor https://github.com/silverstripe/silverstripe-framework/pull/7052

API Update usage of session bootstrapping

---

.travis.yml
composer.json
phpunit.xml.dist
src/Context/BasicContext.php
src/Utility/StepHelper.php
tests/bootstrap.php
tests/php/SilverStripeContextTest.php

Required for https://github.com/silverstripe/silverstripe-framework/pull/7230

Move stepHasTag to trait

---

src/Context/FixtureContext.php

rather than always creating a new
This will open up the option for us to assign the same member multiple groups

Feature use existing fixture for member with the given id if found

---

.travis.yml
composer.json
tests/php/SilverStripeContextTest.php

See silverstripe/silverstripe-framework#7653
Requires silverstripe/silverstripe-framework#7716

API Update to use PHPUnit 7, bump minimum PHP version to 7.1

---

README.md
bin/behat-ss
composer.json
src/Context/BasicContext.php
src/Context/LoginContext.php
src/Context/SilverStripeContext.php
src/MinkExtension.php

Parent story https://github.com/silverstripe/silverstripe-behat-extension/issues/137
Note, after merging, create new 4 branch for this work, re-alias master as 5.x, and reset 3 branch to just before this change.
It is a breaking change, but one we want to support for framework 4.x, and not require framework 5.x.

API Update to use new facebook driver extension
